# Generated by Django 4.0.5 on 2022-07-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EfficiencySiteControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=250, null=True, verbose_name='Ссылка на сайт')),
            ],
            options={
                'verbose_name': 'Список сайтов',
                'verbose_name_plural': 'Список сайтов',
            },
        ),
    ]
