# Generated by Django 4.0.5 on 2022-07-13 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('efficiencySite', '0002_efficiencysitecontrol_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfficiencySiteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('status', models.CharField(max_length=3, null=True, verbose_name='Статус')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='efficiencySite.efficiencysitecontrol', verbose_name='Сайт')),
            ],
        ),
    ]
