# Generated by Django 4.0.5 on 2022-07-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efficiencySite', '0003_efficiencysitestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='efficiencysitecontrol',
            name='statusNow',
            field=models.CharField(max_length=3, null=True, verbose_name='Статус сейчас'),
        ),
    ]
