# Generated by Django 4.0.4 on 2022-06-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineryCategoryNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, null=True, verbose_name='Название')),
                ('description', models.CharField(max_length=355, null=True, verbose_name='Описание')),
                ('price', models.CharField(max_length=11, null=True, verbose_name='Цена покупки')),
            ],
            options={
                'verbose_name': 'Список ноутбуков компании',
                'verbose_name_plural': 'Список ноутбуков компании',
            },
        ),
    ]
