# Generated by Django 4.0.4 on 2022-06-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyMachinery', '0002_machinerycategorynotebook_inventorynumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineryBrandNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True, verbose_name='Название бренда')),
            ],
            options={
                'verbose_name': 'Список брендов ноутбуков',
                'verbose_name_plural': 'Список брендов ноутбуков',
            },
        ),
    ]
