# Generated by Django 3.2.9 on 2022-06-16 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyMachinery', '0003_machinerybrandnotebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinerycategorynotebook',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='companyMachinery.machinerybrandnotebook'),
            preserve_default=False,
        ),
    ]
