# Generated by Django 4.0.5 on 2022-06-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyMachinery', '0004_machinerycategorynotebook_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название категории')),
                ('slug', models.CharField(max_length=50, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Cписок категорий',
                'verbose_name_plural': 'Список категорий',
            },
        ),
        migrations.DeleteModel(
            name='MachineryCategoryNotebook',
        ),
    ]
