# Generated by Django 4.0.5 on 2022-06-22 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyMachinery', '0005_categorylist_delete_machinerycategorynotebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, null=True, verbose_name='Название')),
                ('description', models.CharField(max_length=355, null=True, verbose_name='Описание')),
                ('price', models.CharField(max_length=11, null=True, verbose_name='Цена покупки')),
                ('inventoryNumber', models.CharField(max_length=11, null=True, verbose_name='Инвентаризационный номер')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyMachinery.machinerybrandnotebook', verbose_name='Бред')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyMachinery.categorylist', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Техники',
            },
        ),
    ]
