# Generated by Django 4.0.5 on 2022-06-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyMachinery', '0006_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
