# Generated by Django 4.0.5 on 2022-06-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyMachinery', '0007_rename_product_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylist',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
