# Generated by Django 3.2.9 on 2022-06-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_companyemployees_isactive'),
        ('companyMachinery', '0009_rename_slug_categorylist_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Технику', 'verbose_name_plural': 'Техника'},
        ),
        migrations.AddField(
            model_name='products',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.companyemployees', verbose_name='Категория'),
        ),
    ]
