# Generated by Django 4.0.4 on 2022-05-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_companyemployees_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyemployees',
            name='position',
            field=models.CharField(max_length=50, null=True, verbose_name='Должность'),
        ),
    ]
