# Generated by Django 4.0.4 on 2022-05-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_companyemployees_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyemployees',
            name='isActive',
            field=models.BooleanField(null=True, verbose_name='Активен или нет'),
        ),
    ]
