# Generated by Django 4.0.4 on 2022-05-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_companyemployees_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployees',
            name='isActive',
            field=models.CharField(max_length=5, null=True, verbose_name='Активен или нет'),
        ),
    ]
