# Generated by Django 4.0.4 on 2022-06-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_companyemployees_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployees',
            name='isActive',
            field=models.CharField(max_length=5, verbose_name='Активен или нет'),
        ),
    ]
